routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index');

    Route::prefix('admin')->group(function (){
        Route::get('/login', 'Auth\AdminLoginContoller@ShowLoginForm')->name('admin.login');
        Route::post('/login', 'Auth\AdminLoginContoller@login')->name('admin.login.submit');
        Route::get('/', 'AdminController@index');
    });

Route::resource('categories', 'CategoryController');

Route::resource('categories', 'CategoryController');

Route::resource('categories', 'CategoryController');

Route::resource('products', 'ProductController');

Route::resource('commandes', 'CommandeController');

Route::resource('paniers', 'PanierController');

Route::resource('detailCommandes', 'Detail_commandeController');

Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
);

Auth::routes();

Route::get('/home', 'HomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index');

app/Models/Detail_commande.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Detail_commande
 * @package App\Models
 * @version July 21, 2019, 2:04 am UTC
 *
 * @property \App\Models\Product product
 * @property \App\Models\Commande commande
 * @property integer date
 * @property integer product_id
 * @property integer commande_id
 */
class Detail_commande extends Model
{
    use SoftDeletes;

    public $table = 'detail_commandes';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'date',
        'product_id',
        'commande_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'date' => 'integer',
        'product_id' => 'integer',
        'commande_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function product()
    {
        return $this->belongsTo(\App\Models\Product::class, 'product_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function commande()
    {
        return $this->belongsTo(\App\Models\Commande::class, 'commande_id');
    }
}

app/Http/Controllers/Detail_commandeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateDetail_commandeRequest;
use App\Http\Requests\UpdateDetail_commandeRequest;
use App\Repositories\Detail_commandeRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class Detail_commandeController extends AppBaseController
{
    /** @var  Detail_commandeRepository */
    private $detailCommandeRepository;

    public function __construct(Detail_commandeRepository $detailCommandeRepo)
    {
        $this->detailCommandeRepository = $detailCommandeRepo;
    }

    /**
     * Display a listing of the Detail_commande.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $detailCommandes = $this->detailCommandeRepository->all();

        return view('detail_commandes.index')
            ->with('detailCommandes', $detailCommandes);
    }

    /**
     * Show the form for creating a new Detail_commande.
     *
     * @return Response
     */
    public function create()
    {
        return view('detail_commandes.create');
    }

    /**
     * Store a newly created Detail_commande in storage.
     *
     * @param CreateDetail_commandeRequest $request
     *
     * @return Response
     */
    public function store(CreateDetail_commandeRequest $request)
    {
        $input = $request->all();

        $detailCommande = $this->detailCommandeRepository->create($input);

        Flash::success('Detail Commande saved successfully.');

        return redirect(route('detailCommandes.index'));
    }

    /**
     * Display the specified Detail_commande.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $detailCommande = $this->detailCommandeRepository->find($id);

        if (empty($detailCommande)) {
            Flash::error('Detail Commande not found');

            return redirect(route('detailCommandes.index'));
        }

        return view('detail_commandes.show')->with('detailCommande', $detailCommande);
    }

    /**
     * Show the form for editing the specified Detail_commande.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $detailCommande = $this->detailCommandeRepository->find($id);

        if (empty($detailCommande)) {
            Flash::error('Detail Commande not found');

            return redirect(route('detailCommandes.index'));
        }

        return view('detail_commandes.edit')->with('detailCommande', $detailCommande);
    }

    /**
     * Update the specified Detail_commande in storage.
     *
     * @param int $id
     * @param UpdateDetail_commandeRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateDetail_commandeRequest $request)
    {
        $detailCommande = $this->detailCommandeRepository->find($id);

        if (empty($detailCommande)) {
            Flash::error('Detail Commande not found');

            return redirect(route('detailCommandes.index'));
        }

        $detailCommande = $this->detailCommandeRepository->update($request->all(), $id);

        Flash::success('Detail Commande updated successfully.');

        return redirect(route('detailCommandes.index'));
    }

    /**
     * Remove the specified Detail_commande from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $detailCommande = $this->detailCommandeRepository->find($id);

        if (empty($detailCommande)) {
            Flash::error('Detail Commande not found');

            return redirect(route('detailCommandes.index'));
        }

        $this->detailCommandeRepository->delete($id);

        Flash::success('Detail Commande deleted successfully.');

        return redirect(route('detailCommandes.index'));
    }
}

resources/views/detail_commandes/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Detail Commande
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'detailCommandes.store']) !!}

                        @include('detail_commandes.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/detail_commandes/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Detail Commande
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($detailCommande, ['route' => ['detailCommandes.update', $detailCommande->id], 'method' => 'patch']) !!}

                        @include('detail_commandes.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/detail_commandes/fields.blade.php
<!-- Date Field -->
<div class="form-group col-sm-6">
    {!! Form::label('date', 'Date:') !!}
    {!! Form::date('date', null, ['class' => 'form-control','id'=>'date']) !!}
</div>

@section('scripts')
    <script type="text/javascript">
        $('#date').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: false
        })
    </script>
@endsection

<!-- Product Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('product_id', 'Product Id:') !!}
    {!! Form::text('product_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Commande Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('commande_id', 'Commande Id:') !!}
    {!! Form::text('commande_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('detailCommandes.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/detail_commandes/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Detail Commandes</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('detailCommandes.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('detail_commandes.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/detail_commandes/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Detail Commande
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('detail_commandes.show_fields')
                    <a href="{!! route('detailCommandes.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/detail_commandes/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $detailCommande->id !!}</p>
</div>

<!-- Date Field -->
<div class="form-group">
    {!! Form::label('date', 'Date:') !!}
    <p>{!! $detailCommande->date !!}</p>
</div>

<!-- Product Id Field -->
<div class="form-group">
    {!! Form::label('product_id', 'Product Id:') !!}
    <p>{!! $detailCommande->product_id !!}</p>
</div>

<!-- Commande Id Field -->
<div class="form-group">
    {!! Form::label('commande_id', 'Commande Id:') !!}
    <p>{!! $detailCommande->commande_id !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $detailCommande->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $detailCommande->updated_at !!}</p>
</div>

resources/views/detail_commandes/table.blade.php
<div class="table-responsive">
    <table class="table" id="detailCommandes-table">
        <thead>
            <tr>
                <th>Date</th>
        <th>Product Id</th>
        <th>Commande Id</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($detailCommandes as $detailCommande)
            <tr>
                <td>{!! $detailCommande->date !!}</td>
            <td>{!! $detailCommande->product_id !!}</td>
            <td>{!! $detailCommande->commande_id !!}</td>
                <td>
                    {!! Form::open(['route' => ['detailCommandes.destroy', $detailCommande->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('detailCommandes.show', [$detailCommande->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{!! route('detailCommandes.edit', [$detailCommande->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>